# Generated by Django 4.2.5 on 2023-09-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_bus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.stop', to_field='code'),
        ),
        migrations.AddField(
            model_name='bus',
            name='ts_code',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stop',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='direction',
            field=models.BooleanField(default=False),
        ),
    ]
