# Generated by Django 4.2.5 on 2023-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("order", models.IntegerField()),
                ("direction", models.BooleanField()),
            ],
        ),
    ]
