# Generated by Django 4.2.5 on 2023-09-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_bus_direction_bus_stop_bus_ts_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
